# Generated by Django 4.2.27 on 2026-02-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_lower',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
